APP:
  ENVIRONMENT: test
  DEBUG: True

DATABASE_SERVER:
  HOST: 10.0.0.74
  USER: admin
  PASSWORD: 
  DATABASE: Intelligent_Kitchen


DEBUG_DATABASE_SERVER:
  HOST: 10.0.0.102
  USER: admin
  PASSWORD: 
  DATABASE: Intelligent_Kitchen

DEBUG_SETTING:
  STORE: 1
  DEVICE_NAME: KPS-001-TABLET
  DEVICE_ID: 2
  SENDING_ADDRESS: 10.0.0.54
  SENDING_PORT: 61001
  LISTENING_PORT: 60001



        

